### ISSUE TITLE
NFSv4 support

### ISSUE THREAD

**Issue by gothicx** [xapi-project/sm#30]
I did connect to a CentOS 6.x machine using NFSv4 and the speeds of version 4 of the protocol are great.
I did test it modifying nfs.py and forcing to use mount.nfs4 and it did successfully monted a NFSv4 share.

**Comment by stormi** [comment]
Unless I'm mistaken, this issue can now be closed.

**Comment by MarkSymsCtx** [comment]
Yes, well spotted.
