### ISSUE TITLE
mpath_dmp.py spends 10 seconds in meaningless wait for multipath devices

### ISSUE THREAD

**Issue by alexat** [xapi-project/sm#509]
The culprit is

```
lvm_path = "/dev/disk/by-scsid/"+sid+"/mapper"
util.wait_for_path(lvm_path, 10)
```

There are no /dev/disk/by-scsid/*/mapper files, something is terribly wrong there.

**Comment by alexat** [comment]
It seems this was intended to be
```
lvm_path = "/dev/mapper/"+sid
```

**Comment by MarkSymsCtx** [comment]
The actual issue here is that the /dev/disk/by-scsid/*/mapper symlink is not being created by udev.

**Comment by MarkSymsCtx** [comment]
This https://github.com/xapi-project/sm/pull/510 should resolve the issue.
