### ISSUE TITLE
Missing branch `release/stockholm/lcm` and tag v2.29.1

### ISSUE THREAD

**Issue by stormi** [xapi-project/sm#523]
Hi!

We noticed that there is no `release/stockholm/lcm` maintenance branch, nor the v2.29.1 tag which, I assume, would come from that branch.

Is this something that you intend to push later, or will this repository stop receiving maintenance updates for branches other than master?

Best regards,

Samuel Verschelde

**Comment by MarkSymsCtx** [comment]
maintenance updates are no longer being pushed to this repository.

**Comment by stormi** [comment]
Thanks for the answer.
