### ISSUE TITLE
Make sm works with IPv6

### ISSUE THREAD

**Issue by benjamreis** [xapi-project/sm#527]
Hi all!

I'm trying to play with IPv6 and I'm facing issues when adding a  NFS SR on an IPv6 only pool. Is it currently supported?
If not, what needs to be done?

Here's the error I'm facing:
`SR_BACKEND_FAILURE_1200(, not all arguments converted during string formatting, )`

**Comment by MarkSymsCtx** [comment]
There is no support for IPV6 anywhere in the control domain of the hypervisor.

**Comment by benjamreis** [comment]
I've made some contributions in `xcp-networkd` and `xen-api` to enhance IPv6 support.
I'm experimenting with it right now and have 2 hosts in an IPv6 only pool with many things working so I'm assuming that you're specifically speaking about SMAPI, is that correct?

Do you have an estimation of the work needed to support IPv6? We are willing to help. :)

**Comment by MarkSymsCtx** [comment]
Last estimate was something like 5 man years IIRC.

**Comment by edwintorok** [comment]
It would be good to improve the error message when trying to use IPv6, instead of getting an internal python error about string formatting.

**Comment by olivierlambert** [comment]
5 man years to do what exactly? In SMAPI or in the whole platform? We are not that far to get everything else working (XAPI is almost OK after few PRs, a lot of things are already working).

If it's "just" parsing in SMAPIv1 for few drivers (network SRs) we are willing to improve them.

**Comment by MarkSymsCtx** [comment]
The platform.

**Comment by MarkSymsCtx** [comment]
Big enough and requiring enough testing that our product managers have consistently said no, not happening even though we have customers asking for it.

**Comment by olivierlambert** [comment]
Can you be more specific about which component? From what I'm seeing:

* XAPI (I think we aren't far to get everything done)
* Python install to choose an IPv6 (only minor modification, because the answer file is already capable of eating v6 addresses)
* SMAPIv1 (parsing correctly IPv6 addresses for NFS/iSCSI, anything else?)
* What else?

**Comment by olivierlambert** [comment]
FYI we did release a first ISO with IPv6 support (with 3 modes: IPv4 only/IPv6 only/dual stack). See https://xcp-ng.org/blog/2021/02/09/ipv6-in-xcp-ng/

We'll take a look at SMAPIv1 at least for NFS and iSCSI. @MarkSymsCtx is there any other drivers that would require changes in your opinion?

**Comment by olivierlambert** [comment]
Okay so LVMoiSCSI is already working in IPv6 only :partying_face: 

So there only https://github.com/xapi-project/sm/pull/547 to merge to get NFS in IPv6 and we are done :+1:

**Comment by olivierlambert** [comment]
I'm a bit late but since https://github.com/xapi-project/sm/pull/547 is merged, we should close this.

**Comment by benjamreis** [comment]
indeed!
