### ISSUE TITLE
Resolve IP family of hostname in NFSSR.py

### ISSUE THREAD

**Issue by benjamreis** [xapi-project/sm#596]
HI!

I'm looking for ideas/help in how to resolve a `dconf["server"]` in a NFS device conf before loading the NFS driver on a SR.
If the `server` is a hostname, the transport will default to IPv4 even though the host could be configured in IPv6.
I'm looking at `getaddrinfo` but It can return both IPv4 & 6 for a hostname.
Is there a way to know how the PIF used for the NFS share is configured?

Thanks!

**Comment by MarkSymsCtx** [comment]
Not really as the storage PIFs are not required to be on the same subnet as the target storage appliance just that there exists a route for traffic to traverse to (and back from) the appliance. Which means in the general case you can't even trivially identify which NIC/Bridge will used to route the traffic. There should only be a single DNS being used though and it's really a DNS issue in the case you list above, where you want IPV6 DNS entries to take precedence over the IPV4 addresses. I'm not sure how you'd get this to be the case.

**Comment by MarkSymsCtx** [comment]
Certainly on my IPv6 configured machine sites (e.g. ww.google.com) which are correctly configured for IPV6 enumerate the IPV6 address first in the list of the available addresses.

**Comment by benjamreis** [comment]
Thanks for the quick reply!

Yeah me too, I guess I overthought it and I should simply take the first returned `addrinfo` of `getaddrinfo`.
