### ISSUE TITLE
dev_requirements.txt points to old unusable pylint version

### ISSUE THREAD

**Issue by ydirson** [xapi-project/sm#604]
pylint 1.5 as installed by `pip install -r dev_requirements.txt` aborts with internal failures, on at least CentOS7 and Debian11.

OTOH pylint 2.13.9 does work, but reports a dozen of errors, so it might not be the recommended version either.

**Comment by MarkSymsCtx** [comment]
These files are obsolete and should have been removed, PR raised to do that - https://github.com/xapi-project/sm/pull/605
