### ISSUE TITLE
set archive=1 in /etc/lvm/lvm.conf?

### ISSUE THREAD

**Issue by DSJ2** [xapi-project/sm#635]
From /etc/lvm/lvm.conf:

```
backup {
        # Configuration option backup/archive.
        # Maintain an archive of old metadata configurations.
        # Think very hard before turning this off. 
        archive = 0
```
Note it says **think very hard before turning this off**
Why is archive off in xcp-ng?

Adding this to the SM tracker based on advice in https://github.com/xcp-ng/xcp/issues/619

**Comment by DSJ2** [comment]
Bumping this for attention. Why is LVM archive turned off in XCP-ng?

**Comment by MarkSymsCtx** [comment]
See - https://github.com/xcp-ng/xcp/issues/619#issuecomment-2473185312, this was a change by Redhat in the upstream.
